name: release

on:
  push:
    tags:
      - "[0-9]+\\.[0-9]+"

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - name: create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-archlinux:
    name: build-archlinux
    needs: ['create-release']
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: build package
        id: build_package
        uses: PinkD/arch-pkgbuild-builder@v2.3
        with:
          target: "pkgbuild"
          pkgname: "pack"
      - name: upload package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pack/udp2icmp-${{ github.ref_name }}*.pkg.tar.zst
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: create tarball
        run: |
          cp pack/pkg/udp2icmp/usr/bin/udp2icmp .
          tar -czf udp2icmp-${{ github.ref_name }}-linux-$(uname -m).tar.gz udp2icmp
      - name: upload tarball to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: udp2icmp-${{ github.ref_name }}*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
